### ISSUE TITLE
What is the best way to fully customize the theme?

### ISSUE THREAD

**Issue by RoberMac** [atomiks/tippy.js-react#52]
Currently I make it to `transparent` and use content's styles

```css
.tippy-tooltip.tomato-theme {
  background-color: transparent;
  color: transparent;
}

.tippy-tooltip.tomato-theme[data-animatefill] {
  background-color: transparent;
}

.tippy-tooltip.tomato-theme .tippy-backdrop {
  background-color: transparent;
}

.tippy-popper[x-placement^='top'] .tippy-tooltip.tomato-theme .tippy-arrow {
  border-top-color: transparent;
}
.tippy-popper[x-placement^='bottom'] .tippy-tooltip.tomato-theme .tippy-arrow {
  border-bottom-color: transparent;
}
.tippy-popper[x-placement^='left'] .tippy-tooltip.tomato-theme .tippy-arrow {
  border-left-color: transparent;
}
.tippy-popper[x-placement^='right'] .tippy-tooltip.tomato-theme .tippy-arrow {
  border-right-color: transparent;
}

.tippy-tooltip.tomato-theme .tippy-roundarrow {
  fill: transparent;
}
```
